version: '3'
services:
    web:
        image: meotsa_django_app #django 프로젝트 이미지 이름
        container_name: meotsa_web #django 컨테이너 이름
        command: bash -c "gunicorn modelproject.wsgi:application -b 0.0.0.0:8000" # 서버 실행 #프로젝트 폴더
        ports:
            - '8000:8000'
        restart: always
        volumes:
            - .:/app
            - ./static:/app/static
            - ./media:/app/media # media가 있으면
        networks:
            - server

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
            - ./static:/static
            - ./media:/media # media가 있으면
        restart: unless-stopped
        ports:
            - '80:80'
        depends_on:
            - web
        networks:
            - server

networks:
    server:
        driver: bridge #이 부분 수정
